server:
  port: 8040

spring:
  application:
    name: web-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


logging:
  level:
    org:
      hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: INFO
    your.package.name: INFO