server:
  port: 8080

spring:
  application:
    name: web-service

logging:
  level:
    org:
      hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: INFO
    your.package.name: INFO
