server:
  port: 8040

spring:
  application:
    name: web-service

eureka:
  client:
    service-url:
       #defaultZone: http://192.168.1.106:8761/eureka
       defaultZone: https://eureka.adventuretube.net/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
#logging:
#  level:
#    org:
#      hibernate: INFO
#    org.hibernate.SQL: INFO
#    org.hibernate.type.descriptor.sql: TRACE
#    com.zaxxer.hikari: INFO
#    net.adveturetube: INFO

logging:
  level:
    root: INFO