server:
  port: 8040

spring:
  application:
    name: web-service

eureka:
  instance:
    hostname: 192.168.0.8
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


logging:
  level:
    root: DEBUG