spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: auth-service
  config:
    #using a docker compose
    import: "optional:configserver:http://192.168.1.101:9297"
  devtools:
   restart:
     enabled: true

