spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: auth-service
  config:
    #using a docker compose
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  devtools:
   restart:
     enabled: true

