spring:
  profiles:
    active: native
  application:
    name: auth-service
  config:
    #using a docker compose
    import: "optional:configserver:http://config.adventuretube.net"
  devtools:
   restart:
     enabled: true

