server:
  port: ${AUTH_PORT}

spring:
  datasource:
    url: jdbc:postgresql:${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 2700000
      idle-timeout: 600000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: public
          format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token: ${REFRESH_TOKEN_EXPIRATION}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

geospatial-service:
  url: http://GEOSPATIAL-SERVICE

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.netflix.discovery.DiscoveryClient: WARN
    com.adventuretube.auth: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents,metrics
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}/api/v2/spans

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      MEMBER-SERVICE:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      GEOSPATIAL-SERVICE:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      MEMBER-SERVICE:
        timeout-duration: 5s
      GEOSPATIAL-SERVICE:
        timeout-duration: 5s
