eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: https://eureka.adventuretube.net/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
