
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - adventuretube-jenkins-network
    ports:
      - 2181:2181
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://zookeeper:2181" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
        - zookeeper_data:/var/lib/zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - adventuretube-jenkins-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.1.101:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka

networks:
  adventuretube-jenkins-network:
    driver: bridge
    name : adventuretube-jenkins-network
volumes:
  zookeeper_data:
  kafka_data: