services:
  postgres:
    image: postgres:latest # Use the latest version, or specify a version (e.g., postgres:15)
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5785Ch00
      - POSTGRES_DB=adventuretube
    networks:
      - adventuretube-jenkins-network
    restart: no

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest # Use the latest version, or specify a version
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-strider.lee@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-5785Ch00}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - adventuretube-jenkins-network
    restart: no

  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=strider
      - MONGO_INITDB_ROOT_PASSWORD=5785Ch00
    networks:
      - adventuretube-jenkins-network
    restart: no

  mongo-express:
    image: mongo-express:latest # Use the latest version, or specify a version
    container_name: mongo-express
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=strider
      - ME_CONFIG_MONGODB_ADMINPASSWORD=5785Ch00
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - adventuretube-jenkins-network
    restart: no


networks:
  adventuretube-jenkins-network:
    driver: bridge
    name : adventuretube-jenkins-network





volumes:
  postgres:
  pgadmin:
  mongodb_data:
