services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8010:8010"
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#      #- SPRING_PROFILES_ACTIVE=prod
    networks:
      - adventuretube-jenkins-network
    restart: on-failure


  member-service:
    image: member-service:latest
    build:
      context: ./member-service
      dockerfile:  ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8070:8070"
    #    environment:
    #      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #      #- SPRING_PROFILES_ACTIVE=prod
    networks:
      - adventuretube-jenkins-network
    restart: on-failure

  geospatial-service:
    image: geospatial-service:latest
    build:
      context: ./geospatial-service
      dockerfile:  ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8060:8060"
    #    environment:
    #      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #      #- SPRING_PROFILES_ACTIVE=prod
    networks:
      - adventuretube-jenkins-network
    restart: on-failure


networks:
  adventuretube-jenkins-network:
   driver: bridge
   name : adventuretube-jenkins-network

