version: "3.9"

services:
  auth-service:
    build:
      context: . # Context points to the module folder
      dockerfile: ${Dockerfile} # Unified Dockerfile.mac located in the root directory
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        MODULE_NAME: auth-service
        APP_PORT: ${AUTH_SERVICE_PORT}
        DEBUG_PORT: ${AUTH_DEBUG_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
      - "${AUTH_DEBUG_PORT}:${AUTH_DEBUG_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_DEBUG_PORT=${AUTH_DEBUG_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:${AUTH_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

  member-service:
    build:
      context: . # Context points to the module folder
      dockerfile: ${Dockerfile} # Unified Dockerfile.mac located in the root directory
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        MODULE_NAME: member-service
        APP_PORT: ${MEMBER_SERVICE_PORT}
        DEBUG_PORT: ${MEMBER_DEBUG_PORT}
    ports:
      - "${MEMBER_SERVICE_PORT}:${MEMBER_SERVICE_PORT}"
      - "${MEMBER_DEBUG_PORT}:${MEMBER_DEBUG_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_DEBUG_PORT=${MEMBER_DEBUG_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${MEMBER_DEBUG_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://member-service:${MEMBER_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

  web-service:
    build:
      context: . # Context points to the module folder
      dockerfile: ${Dockerfile} # Unified Dockerfile.mac located in the root directory
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        MODULE_NAME: web-service
        APP_PORT: ${WEB_SERVICE_PORT}
        DEBUG_PORT: ${WEB_DEBUG_PORT}
    ports:
      - "${WEB_SERVICE_PORT}:${WEB_SERVICE_PORT}"
      - "${WEB_DEBUG_PORT}:${WEB_DEBUG_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_DEBUG_PORT=${WEB_DEBUG_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${WEB_DEBUG_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web-service:${WEB_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

  geospatial-service:
    build:
      context: . # Context points to the module folder
      dockerfile: ${Dockerfile} # Unified Dockerfile.mac located in the root directory
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        MODULE_NAME: geospatial-service
        APP_PORT: ${GEOSPATIAL_SERVICE_PORT}
        DEBUG_PORT: ${GEOSPATIAL_DEBUG_PORT}
    ports:
      - "${GEOSPATIAL_SERVICE_PORT}:${GEOSPATIAL_SERVICE_PORT}"
      - "${GEOSPATIAL_DEBUG_PORT}:${GEOSPATIAL_DEBUG_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_DEBUG_PORT=${GEOSPATIAL_DEBUG_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${GEOSPATIAL_DEBUG_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://geospatial-service:${GEOSPATIAL_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

networks:
  adventuretube-jenkins-network:
    driver: bridge
    name: adventuretube-jenkins-network
