services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8010:8010"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth-service:8010/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  member-service:
    image: member-service:latest
    build:
      context: ./member-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://member-service:8070/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  web-service:
    image: web-service:latest
    build:
      context: ./web-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8040:8040"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://web-service:8040/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  geospatial-service:
    image: geospatial-service:latest
    build:
      context: ./geospatial-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8060:8060"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://geospatial-service:8060/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

networks:
  adventuretube-jenkins-network:
    driver: bridge
    name: adventuretube-jenkins-network
