services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8010:8010"
      - "5005:5005"  # Expose debug port for auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_DEBUG_PORT=5005
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth-service:8010/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  member-service:
    image: member-service:latest
    build:
      context: ./member-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8070:8070"
      - "5006:5006"  # Expose debug port for member-service
    environment:
      - JAVA_DEBUG_PORT=5006
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://member-service:8070/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  web-service:
    image: web-service:latest
    build:
      context: ./web-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8040:8040"
      - "5007:5007"  # Expose debug port for web-service
    environment: # From https://blairnangle.com/blog/spring-boot-docker-compose-debug
      - JAVA_DEBUG_PORT=5007
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://web-service:8040/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no
  geospatial-service:
    image: geospatial-service:latest
    build:
      context: ./geospatial-service
      dockerfile: ${DOCKERFILE:-Dockerfile.pi}
    ports:
      - "8060:8060"
      - "5008:5008"  # Expose debug port for geospatial-service
    environment:
      - JAVA_DEBUG_PORT=5008
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://geospatial-service:8060/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adventuretube-jenkins-network
    restart: no

networks:
  adventuretube-jenkins-network:
    driver: bridge
    name: adventuretube-jenkins-network
