server:
  port: 8070

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:postgresql://adventuretube.net:5432/adventuretube
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

eureka:
  instance:
    hostname: 192.168.0.8
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


logging:
  level:
    root: DEBUG
