eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/api/web
logging:
  level:
    root: INFO
server:
  port: 8010
