spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}


logging:
  level:
    root: INFO  # Set the logging level for the entire application
    com.adventuretube: DEBUG  # More detailed logging for your application's package
