eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: https://eureka.adventuretube.net/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web/**
logging:
  level:
    root: INFO
server:
  port: 8080
