server:
  port: 8050

spring:
  application:
    name: security-service

eureka:
  instance:
    hostname: 192.168.0.8
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
     defaultZone: https://eureka.adventuretube.net/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


logging:
  level:
    org:
      hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: INFO
    your.package.name: INFO


jwt.secret  : adventuretube