server:
  port: 8050

spring:
  application:
    name: security-service

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
     defaultZone: https://eureka.adventuretube.net/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


logging:
  level:
    root: DEBUG

jwt:
  secret: adventuretubeMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400