server:
  port: 8070

spring:
  application:
    name: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/adventuretube
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema:
          format_sql: true