spring:
  application:
    name: eureka-server

server:
  port: 8761  # Default port for all environments unless overridden

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}  # Assuming hostname resolution is set up
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO  # Set the logging level for the entire application
    com.adventuretube: DEBUG  # More detailed logging for your application's package
    com.adventuretube.config.DotenvEnvironmentPostProcessor: INFO
