version: '3.8'
services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    environment:
      KSQL_CONFIG_DIR: /etc/ksqldb
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8088:8088
    depends_on:
      - kafka

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    stdin_open: true
    tty: true
    depends_on:
      - ksqldb-server
