version: '3.9'

services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER  # New line to specify the controller listener
    entrypoint:
      - /bin/bash
      - -c
      - |
        export CLUSTER_ID=$(kafka-storage random-uuid)
        echo "Generated CLUSTER_ID: $CLUSTER_ID"
        kafka-storage format --ignore-formatted --cluster-id=$CLUSTER_ID -t /var/lib/kafka/data
        /etc/confluent/docker/run
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9092:9092"

volumes:
  kafka_data:
