version: '3.8'
services:
  connect:
    image: confluentinc/cp-kafka-connect:latest
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins
    ports:
      - 8083:8083
    depends_on:
      - kafka
    volumes:
      - ./plugins:/etc/kafka-connect/plugins
