server:
  port: 9297
  tomcat:
    apr:
      enabled: false

spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      server:
        git:
          uri: git@github.com:strider73/adventuretube-microservice.git
          clone-on-start: true
          search-paths: config-service/src/main/resources/config
          default-label: add-kafka
  logging:
    level:
      org.springframework.cloud.config.server: DEBUG
      org.springframework.cloud.config: DEBUG
      org.eclipse.jgit: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.116:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env,configprops
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    env:
      show-details: always
    health:
      show-details: always

