server:
  port: 9297
  tomcat:
      apr:
        enabled:false
spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      server:
        git:
          uri: git@github.com:strider73/adventuretube-microservice.git
          clone-on-start: true
          search-paths: config-service/src/main/resources/config
          default-label: add-kafka
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config




eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.116:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#logging:
#  level:
#    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always

