spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/strider73/adventuretube-microservice.git
          clone-on-start: true
          search-paths: config-service/src/main/resources/config
          default-label: add-kafka
  profiles:
    active: git  # Default profile for Git backend

server:
  port: 9297
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
